site_name: Docs2 Sample
nav:
  - Welcome: index.md
  - Tutorials:
      - Getting Started: tutorials/getting-started.md
      - Advanced Paths: tutorials/advanced-topics.md
      - broken path: tootrials/advanced-topics.md
      - Not there: tutorials/missing.md 
  - API: api.md
